name=PCBCUPID_PLAYERS
version=1.0.0
author=Karthik Elumalai <codingkarthik2@gmail.com>
maintainer=PCBCUPID <hello@pcbcupid.com>
sentence=Audio player library for ESP32 with SD card, I2S output, and NAU8325 codec with amplifier control.
paragraph=High-level audio player library for Glyph ESP32(H2,C3,C6) and Arduino-compatible boards. Supports MP3, WAV, OGG, AAC playback from SD card, I2S digital audio output, and NAU8325 Codec with Class-D amplifier control via I2C. Includes playlist management, volume, metadata, and easy integration.
category=Signal Input/Output
url=https://github.com/pcbcupid/PCBCUPID-PLAYER
architectures=esp32
includes=PCBCUPID_PLAYERS.h
depends=AudioTools,Arduino-Audio-Driver,SD,Wire